//--------------------------------------------------------------- 
//-- Verilog Parameters generated by MATLAB 
//--------------------------------------------------------------- 
parameter           XY_WIDTH                          = 26;
parameter           Z_WIDTH                           = 18;
parameter           ITER                              = 16;
//--------------------------------------------------------------- 
//-- Verilog Parameters required by gain compensation logic 
parameter           X_GAIN_EXT_BITS                   = 0;
parameter           GAIN_MODEL                        = 1;	
parameter           RECIP_GAIN                        = 32'h7FFFFFFF;	
//--------------------------------------------------------------- 
parameter           ATAN_0                            = 18'h08000;	
parameter           ATAN_1                            = 18'h04B90;	
parameter           ATAN_2                            = 18'h027ED;	
parameter           ATAN_3                            = 18'h01444;	
parameter           ATAN_4                            = 18'h00A2C;	
parameter           ATAN_5                            = 18'h00517;	
parameter           ATAN_6                            = 18'h0028C;	
parameter           ATAN_7                            = 18'h00146;	
parameter           ATAN_8                            = 18'h000A3;	
parameter           ATAN_9                            = 18'h00051;	
parameter           ATAN_10                            = 18'h00029;	
parameter           ATAN_11                            = 18'h00014;	
parameter           ATAN_12                            = 18'h0000A;	
parameter           ATAN_13                            = 18'h00005;	
parameter           ATAN_14                            = 18'h00003;	
parameter           ATAN_15                            = 18'h00001;	
parameter           ATAN_16                            = 18'h00001;	
parameter           ATAN_17                            = 18'h00000;	
parameter           ATAN_18                            = 18'h00000;	
parameter           ATAN_19                            = 18'h00000;	
parameter           ATAN_20                            = 18'h00000;	
parameter           ATAN_21                            = 18'h00000;	
parameter           ATAN_22                            = 18'h00000;	
parameter           ATAN_23                            = 18'h00000;	
parameter           ATAN_24                            = 18'h00000;	
parameter           ATAN_25                            = 18'h00000;	
parameter           ATAN_26                            = 18'h00000;	
parameter           ATAN_27                            = 18'h00000;	
parameter           ATAN_28                            = 18'h00000;	
parameter           ATAN_29                            = 18'h00000;	
parameter           ATAN_30                            = 18'h00000;	
parameter           ATAN_31                            = 18'h00000;	
